max_num_words : 20
max_num_nodes : 20
max_num_frames : 64 # for charades, 64
iou : [0.1, 0.3, 0.5, 0.7]
batch_size : 12 
word_dim : 300 # 768 for tvr else 300
frame_dim : 1024 # 500 for act, 1024 for char, 4096 for did/msr/tac, 3072 for tvr, 512 for you 
is_adj: False
with_max_IoU : 0.3
vocab_size: 300

MODEL:
  ARCHITECTURE: "TRM"
  TRM:
    NUM_CLIPS: 16
    JOINT_SPACE_SIZE: 300 # 512, 300
    RESIDUAL: 1.0
    FEATPOOL:
      INPUT_SIZE: 1024 # 1024, 4096
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 2
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15]
    TEXT_ENCODER:
      NAME: "BERT"
      USE_PHRASE: True
      DROP_PHRASE: True
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 5
      NUM_STACK_LAYERS: 8
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.4
      CONTRASTIVE_WEIGHT: 0.05
      SENT_NEG_IOU: 0.5
      NEGATIVE_PROP_IOU: 0.5
      PHRASE_ONLY: False
      USE_SCORE_MAP_LOSS: True
      USE_FOCAL_LOSS: True
      CONTRASTIVE: True
      CONSIS_WEIGHT: 1.0
      EXC_WEIGHT: 0.0
      THRESH: 0.1
DATASETS:
  NAME: "charades"
  TRAIN: ("charades_train", )
  TEST: ("charades_test","charades_test_verb",)
INPUT:
  NUM_PRE_CLIPS: 64 # 32
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0001
  BATCH_SIZE: 12 # 12
  MILESTONES: (8, 13)
  MAX_EPOCH: 18 # 18 
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 7
  FREEZE_BERT: 2 # 2
  ONLY_IOU: 7 # 7
  SKIP_TEST: 0
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 48
  CONTRASTIVE_SCORE_POW: 0.5
