max_num_words : 20
max_num_nodes : 20
max_num_frames : 256 #  64 for charades else 200
iou : [0.1, 0.3, 0.5, 0.7]
batch_size : 24 
word_dim : 300 # 768 for tvr else 300
frame_dim : 512 # 500 for act, 1024 for char, 4096 for did/msr/tac, 3072 for tvr, 512 for you 
is_adj: False
with_max_IoU : 0.3
vocab_size: 300

MODEL:
  ARCHITECTURE: "TRM"
  TRM:
    NUM_CLIPS: 64
    JOINT_SPACE_SIZE: 300
    RESIDUAL: 0.1
    FEATPOOL:
      INPUT_SIZE: 512 # 500 for act, 1024 for char, 4096 for did/msr/tac, 3072 for tvr, 512 for you 
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 4
    FEAT2D:
      NAME: "pool"
      POOLING_COUNTS: [15, 8, 8]
    TEXT_ENCODER:
      NAME: "BERT"
      USE_PHRASE: True
      DROP_PHRASE: False
    PREDICTOR:
      HIDDEN_SIZE: 512
      KERNEL_SIZE: 9
      NUM_STACK_LAYERS: 4
    LOSS:
      MIN_IOU: 0.5
      MAX_IOU: 1.0
      NUM_POSTIVE_VIDEO_PROPOSAL: 1
      NEGATIVE_VIDEO_IOU: 0.5
      SENT_REMOVAL_IOU: 0.5
      TAU_VIDEO: 0.1
      TAU_SENT: 0.1
      MARGIN: 0.3
      CONTRASTIVE_WEIGHT: 0.01
      SENT_NEG_IOU: 0.5
      NEGATIVE_PROP_IOU: 0.5
      PHRASE_ONLY: False
      USE_SCORE_MAP_LOSS: True
      USE_FOCAL_LOSS: True
      CONTRASTIVE: True
      CONSIS_WEIGHT: 0.0
      EXC_WEIGHT: 0.0
      THRESH: 0.2
DATASETS:
  NAME: "youcook2"
  TRAIN: ("youcook2_train", )
  TEST: ("youcook2_test","youcook2_test_verb")
INPUT:
  NUM_PRE_CLIPS: 256 # 256
DATALOADER:
  NUM_WORKERS: 16
SOLVER:
  LR: 0.0008
  BATCH_SIZE: 24
  MILESTONES: (15,)
  MAX_EPOCH: 18
  TEST_PERIOD: 1
  CHECKPOINT_PERIOD: 1
  RESUME: False
  RESUME_EPOCH: 10
  FREEZE_BERT: 4
  ONLY_IOU: 6
  SKIP_TEST: 0
TEST:
  NMS_THRESH: 0.5
  BATCH_SIZE: 24
  CONTRASTIVE_SCORE_POW: 0.5
