max_num_words : 64
max_num_nodes : 20
max_num_frames : 200
iou : [0.1, 0.3, 0.5, 0.7]
is_adj: False
with_max_IoU : 0.3

# model config
data_name: 'you_precomp'
margin: 0.2
batch_size: 128
vocab_size: 300
word_dim: 300
embed_size: 1024
finetune: False
cnn_type: 'vgg19'
grad_clip: 2.
crop_size: 224
num_layers: 1
workers: 10
max_violation: False
img_dim: 512 # 4096, 1024
measure: 'cosine'
use_abs: False
no_imgnorm: False

# training config
early_stop_patience : 25
lr : 0.001
lr_drop_step : 30
wd : 0
optimizer : 'adam'
scheduler : 'steplr'
gamma : 0.1