# activity, tacos, charades, didemo
max_num_words : 20
max_num_nodes : 20
max_num_frames : 256 # 64 for charades else 200
d_model : 512
num_heads : 4
batch_size : 64 
dropout : 0.2
word_dim : 300 # 768 for tvr else 300
frame_dim : 1024 # 500 for act, 1024 for char, 4096 for did/msr/tac, 3072 for tvr, 512 for you 
iou : [0.1, 0.3, 0.5, 0.7]
is_adj : False
with_max_IoU : False
vocab_size : 1111

WORKERS: 16

MODEL_DIR: ./checkpoints/checkpoints-paper
RESULT_DIR: ./infer_results
LOG_DIR: ./log/log-paper
DATA_DIR: ./data/Charades-STA
EXPERIMENT_CFG: vgg-mgpn256

DATASET:
  NAME: Charades
  VIS_INPUT_TYPE: charades_vgg_rgb
  NO_VAL: True
  NUM_SAMPLE_CLIPS: 256
  TARGET_STRIDE: 16
  NORMALIZE: True
  RANDOM_SAMPLING: False

TEST:
  BATCH_SIZE: 32
  RECALL: 1,5
  TIOU: 0.3,0.5,0.7
  EVAL_TRAIN: False
  NMS_THRESH: 0.44

CUDNN:
  DETERMINISTIC: False
  BENCHMARK: True

TRAIN:
  BATCH_SIZE: 32
  LR: 0.001
  WEIGHT_DECAY: 0.0000
  MAX_EPOCH: 15
  CONTINUE: False
  STEPSIZE: 15
  GAMMA: 0.1
  MILESTONES: [5,12]


LOSS1:
  NAME: bce_rescale_loss
  PARAMS:
    MIN_IOU: 0.5
    MAX_IOU: 1.0
    BIAS: 0.0

MGPN:

  COARSE_GRAINED_ENCODER:
    NAME: FeatureEncoder
    PARAMS:
      FRAME:
        INPUT_SIZE: 4096
        HIDDEN_SIZE: 256
        KERNEL_SIZE: 16
        STRIDE: 16
        USE_POSITION: False
        NUM_CLIPS: 16
      GRU:
        TXT_INPUT_SIZE: 300
        TXT_HIDDEN_SIZE: 256
        VIS_INPUT_SIZE: 256
        VIS_HIDDEN_SIZE: 256
        NUM_LAYERS: 2
        BIDIRECTIONAL: True
  
  COATTENTION_MODULE:
    NAME: FirstFuse
    PARAMS:
      HIDDEN_SIZE: 256
      TXT_INPUT_SIZE: 256
      VIS_INPUT_SIZE: 256
      NUM_CLIPS: 16

  CHOICE_GENERATOR:
    NAME: SparseBoundaryContent
    PARAMS:
      NUM_CLIPS: 16
      NUM_SCALE_LAYERS: [15]

  FINE_GRAINED_ENCODER:
    NAME: FineGrainedFeature
    PARAMS:
      VIS_INPUT_SIZE: 256
      VIS_HIDDEN_SIZE: 256
      VIS_OUTPUT_SIZE: 256
      TXT_INPUT_SIZE: 256
      TXT_OUTPUT_SIZE: 256

  CONDITIONED_INTERACTION_MODULE:
    NAME: SecondFuse
    PARAMS:
      HIDDEN_SIZE: 256
      TXT_INPUT_SIZE: 256
      VIS_INPUT_SIZE: 256
      NUM_CLIPS: 16
        
  CHOICE_COMPARISON_MODULE:
    NAME: ConvModule
    PARAMS:
      INPUT_SIZE: 256
      OUTPUT_SIZE: 256
      INTER_PROP: 4
      BLOCK_NUM: 2
      LOOP_NUM: 2

  PRED_INPUT_SIZE: 256


MODEL:
  NAME: MGPN
  CHECKPOINT: ./checkpoints/checkpoints-paper/Charades/vgg-mgpn256-.pkl
