max_num_words : 20
max_num_nodes : 20
max_num_frames : 256 # for charades, 64
d_model : 512
num_heads : 4
batch_size : 32
dropout : 0.2
word_dim : 300
frame_dim : 500
num_gcn_layers : 2
num_attn_layers : 2
iou : [0.1, 0.3, 0.5, 0.7]
is_adj : False

WORKERS: 4

MODEL_DIR: ./checkpoints/checkpoints-paper
RESULT_DIR: ./infer_results
LOG_DIR: ./log/log-paper
DATA_DIR: ./data/ActivityNet
EXPERIMENT_CFG: dynamic+gat

DATASET:
  NAME: ActivityNet
  VIS_INPUT_TYPE: c3d
  NO_VAL: True
  NUM_SAMPLE_CLIPS: 256
  TARGET_STRIDE: 4
  NORMALIZE: True
  RANDOM_SAMPLING: False

TEST:
  BATCH_SIZE: 64
  RECALL: 1,5
  TIOU: 0.3,0.5,0.7
  EVAL_TRAIN: False
  NMS_THRESH: 0.52

CUDNN:
  DETERMINISTIC: False
  BENCHMARK: True

TRAIN:
  BATCH_SIZE: 64
  LR: 0.001
  WEIGHT_DECAY: 0.0000
  MAX_EPOCH: 15
  CONTINUE: False
  # STEPSIZE: 15
  GAMMA: 0.1
  MILESTONES: [5,9]

LOSS1:
  NAME: bce_rescale_loss
  PARAMS:
    MIN_IOU: 0.5
    MAX_IOU: 1.0
    BIAS: 0.0

RANET:

  ENCODER_LAYER:
    NAME: FeatureEncoder
    PARAMS:
      FRAME:
        INPUT_SIZE: 500
        HIDDEN_SIZE: 512
        KERNEL_SIZE: 4
        STRIDE: 4
        USE_POSITION: True
        NUM_CLIPS: 64
      GCNEXT:
        INPUT_SIZE: 512
        OUTPUT_SIZE: 512
        K_NUM: 5
        GROUP_NUM: 32
        WIDTH_GROUP: 4
      LSTM:
        TXT_INPUT_SIZE: 300
        TXT_HIDDEN_SIZE: 512
        NUM_LAYERS: 3
        BIDIRECTIONAL: True

  GNERATOR_LAYER:
    NAME: SparseBoundaryCat
    PARAMS:
      NUM_CLIPS: 64
      NUM_SCALE_LAYERS: [15,8,8]

  INTERACTOR_LAYER:
    NAME: DynamicFuse
    PARAMS:
      HIDDEN_SIZE: 512
      TXT_INPUT_SIZE: 512
      VIS_INPUT_SIZE: 1024
        
  RELATION_LAYER:
    NAME: GATModule
    PARAMS:
      INPUT_SIZE: 512
      OUTPUT_SIZE: 512
      INTER_PROP: 4
      BLOCK_NUM: 1
      LOOP_NUM: 2

  PRED_INPUT_SIZE: 512


MODEL:
  NAME: RaNet
  CHECKPOINT: ./checkpoints/best/ActivityNet/dynamic+gat-2867.pkl